# Bu dosya içerisinde aslında normalde tensorflow ile yaptığımız işlemlerin Pytorch halini göreceksiniz.Ama en önce neden pytorch ve neden Tensorler ? Gelin beraber inceleyelim.

---

# PyTorch ile Yapay Sinir Ağlarına Giriş

Yapay zekâ ve derin öğrenme alanında **PyTorch**, esnek yapısı ve dinamik hesaplama grafiği sayesinde en çok tercih edilen kütüphanelerden biridir.  
Özellikle araştırma, prototipleme ve hızlı denemeler yapmak için sunduğu **kolay kullanım** ve **GPU hızlandırma** desteği ile öne çıkar.  

## Neden PyTorch?

- **Dinamik hesaplama grafiği**: Modeli adım adım değiştirmek ve hata ayıklamak kolaydır.  
- **Kolay öğrenim eğrisi**: Python’a yakın bir yazım şekli olduğundan anlaşılır.  
- **Geniş ekosistem**: TorchVision, TorchText, TorchAudio gibi yan kütüphanelerle desteklenir.  
- **Araştırma ve üretim uyumluluğu**: Hem akademide hem de endüstride yaygınca kullanılır.  

## PyTorch Kullanırken Nelere Dikkat Etmeli?

- **Tensor mantığını anlamak**: PyTorch’un kalbi `Tensor` veri yapısıdır.  
- **CUDA / GPU kullanımı**: `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")` ile GPU’dan faydalanmayı unutmamak gerekir.  
- **Model – loss – optimizer üçlüsü**: Eğitim döngüsünde bu üç yapı sürekli birlikte çalışır.  
- **Autograd sistemi**: Geriye yayılım (`backward`) işlemlerini otomatik yapar, ama `with torch.no_grad():` gibi durumlarda manuel kontrol gerekebilir.  
- **Batch işlemleri**: Eğitim sırasında verileri tek tek değil, gruplar (batch) halinde beslemek performans açısından kritik öneme sahiptir.  

---


# PyTorch’ta Tensor Nedir?

## 🔹 Teorik Tanım
- **Tensor**, çok boyutlu sayı dizisidir.  
- Aslında **vektör** ve **matris** kavramlarının daha genel halidir.  

### Örnekler:
- **Skaler (0D tensor)** → Tek sayı  
  `x = 5`  
- **Vektör (1D tensor)** → Sayı listesi  
  `[1, 2, 3]`  
- **Matris (2D tensor)** → Tablo şeklinde sayılar  
  `[[1, 2], [3, 4]]`  
- **Yüksek boyutlu tensorler (3D, 4D, …)** →  
  - Görseller (3D: yükseklik × genişlik × kanal)  
  - Videolar (4D: zaman × yükseklik × genişlik × kanal)  



## 🔹 PyTorch’ta Tensor
- `torch.Tensor`, NumPy array’e çok benzer.  
- GPU üzerinde çalışabilir.  
- Yapay sinir ağlarındaki **girdiler, çıktılar ve ağırlıklar** hep tensor olarak saklanır.  





---

## 🔹 Neden Tensor, NumPy Değil?

1. **GPU Desteği**  
   Tensor verileri CPU’dan GPU’ya taşıyabilir → hesaplamalar çok hızlanır.  

   ```python
   import torch
   x = torch.tensor([1, 2, 3], dtype=torch.float32)

 ## 🔹 Otomatik Türev (autograd)

Derin öğrenmede türev hesaplamak gerekir. Tensor bunu kendisi yapar.

In [1]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()
print(x.grad)  # 2x = 4


tensor(4.)


## 🔹 PyTorch Ekosistemi
Model, katman, optimizer, loss fonksiyonu → hepsi Tensor ile çalışır.
NumPy burada uyumsuz kalır.

----

# Tensor ve NumPy Array Karşılaştırması

## 🔹 2D Tensor Örneği (PyTorch)


In [ ]:
import torch

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print("Tensor:\n", tensor)
print("Boyutları:", tensor.shape)
print("Cihaz:", tensor.device)

Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Boyutları: torch.Size([2, 3])
Cihaz: cpu


## 🔹 2D NumPy Array Örneği

In [6]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("NumPy Array:\n", array)
print("Boyutları:", array.shape)


NumPy Array:
 [[1 2 3]
 [4 5 6]]
Boyutları: (2, 3)


| Özellik             | NumPy Array | PyTorch Tensor |
| ------------------- | ----------- | -------------- |
| Boyut               | Çok boyutlu | Çok boyutlu    |
| GPU Desteği         | ❌           | ✅              |
| Otomatik Türev      | ❌           | ✅              |
| Derin öğrenme uyumu | ❌           | ✅              |


---

# PyTorch Tensor Temel İşlemler

## 🔹 1. Toplama ve Çıkarma
```python
import torch

# 1D Tensor
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Toplama
c = a + b
print("Toplama:", c)  # [5, 7, 9]

# Çıkarma
d = b - a
print("Çıkarma:", d)  # [3, 3, 3]


----

# PyTorch Tensor: Şekil Değiştirme ve Slicing

## 🔹 1. Reshape (Boyut Değiştirme)

* view ile tensor boyutunu değiştiririz. Yeni boyut orijinal eleman sayısıyla uyumlu olmalı.


In [8]:
import torch

x = torch.tensor([[1,2,3],
                  [4,5,6]])
print("Orijinal Tensor:\n", x, "Şekil:", x.shape)

# 2x3 -> 3x2
y = x.view(3,2)
print("Reshape 3x2:\n", y)


Orijinal Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]]) Şekil: torch.Size([2, 3])
Reshape 3x2:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


## 🔹 2. Boyut Eklemek / Çıkarmak

In [7]:
x = torch.tensor([1,2,3])
print("Orijinal:", x, "Şekil:", x.shape)

# Boyut ekleme (1D -> 2D)
x_unsqueeze = x.unsqueeze(0)
print("unsqueeze(0) ile yeni boyut:", x_unsqueeze.shape)

# Boyut çıkarmak
x_squeeze = x_unsqueeze.squeeze(0)
print("squeeze(0) ile eski boyut:", x_squeeze.shape)


Orijinal: tensor([1, 2, 3]) Şekil: torch.Size([3])
unsqueeze(0) ile yeni boyut: torch.Size([1, 3])
squeeze(0) ile eski boyut: torch.Size([3])


## 🔹 3. Slicing (Eleman Seçme)

In [9]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])
# Satır seçme
print("0. Satır:", x[0])

# Sütun seçme
print("1. Sütun:", x[:,1])

# Alt matris seçme
print("Alt matris:\n", x[0:2,1:3])


0. Satır: tensor([1, 2, 3])
1. Sütun: tensor([2, 5])
Alt matris:
 tensor([[2, 3],
        [5, 6]])


----

# PyTorch Tensor: İleri İşlemler

## 🔹 1. Tensor Birleştirme (Concatenation)

In [10]:
import torch

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

# Satır bazında birleştirme (dim=0)
c = torch.cat((a,b), dim=0)
print("Satır bazında birleştirme:\n", c)

# Sütun bazında birleştirme (dim=1)
d = torch.cat((a,b), dim=1)
print("Sütun bazında birleştirme:\n", d)

Satır bazında birleştirme:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Sütun bazında birleştirme:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 🔹 2. Temel İstatistik İşlemleri

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])

print("Toplam:", x.sum())
print("Satır bazında toplam:", x.sum(dim=1))
print("Sütun bazında toplam:", x.sum(dim=0))

print("Ortalama:", x.float().mean())
print("Max değer:", x.max())
print("Min değer:", x.min())


Toplam: tensor(21)
Satır bazında toplam: tensor([ 6, 15])
Sütun bazında toplam: tensor([5, 7, 9])
Ortalama: tensor(3.5000)
Max değer: tensor(6)
Min değer: tensor(1)


## 🔹 3. Eleman Bazlı İşlemler

In [12]:
x = torch.tensor([1,2,3,4])

print("Karesi:", x**2)
print("Kök:", torch.sqrt(x.float()))
print("Logaritma:", torch.log(x.float()))


Karesi: tensor([ 1,  4,  9, 16])
Kök: tensor([1.0000, 1.4142, 1.7321, 2.0000])
Logaritma: tensor([0.0000, 0.6931, 1.0986, 1.3863])
